language: ruby
exclude: [vendor]
rvm:
- 2.1
before_script:
 - chmod +x ./script
script: bundle exec jekyll build && bundle exec htmlproof ./_site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer